/**
 * Scaffold Command - Generate handler functions from contract ABI
 */

import chalk from 'chalk';
import ora from 'ora';
import * as fs from 'fs-extra';
import * as path from 'path';

interface ScaffoldOptions {
  output?: string;
  includeView?: boolean;
  includePure?: boolean;
}

interface ABIItem {
  type: string;
  name?: string;
  inputs?: Array<{
    name: string;
    type: string;
    internalType?: string;
  }>;
  outputs?: Array<{
    name: string;
    type: string;
  }>;
  stateMutability?: string;
}

export async function scaffoldCommand(
  contract: string,
  options: ScaffoldOptions
): Promise<void> {
  console.log(chalk.bold('\n🔧 Scaffolding Handler Functions\n'));

  const spinner = ora('Loading contract ABI...').start();

  try {
    // Load ABI
    let abi: ABIItem[];
    
    if (contract.endsWith('.json')) {
      // Direct ABI file
      const abiContent = await fs.readJSON(contract);
      abi = abiContent.abi || abiContent;
    } else {
      // Try to find in Foundry output
      const outPath = path.join(process.cwd(), 'out', `${contract}.sol`, `${contract}.json`);
      if (await fs.pathExists(outPath)) {
        const artifact = await fs.readJSON(outPath);
        abi = artifact.abi;
      } else {
        spinner.fail(`Could not find ABI for ${contract}`);
        console.log(chalk.gray(`  Tried: ${outPath}`));
        console.log(chalk.gray('  Run "forge build" first or provide a direct path to ABI file'));
        process.exit(1);
      }
    }

    spinner.text = 'Generating handlers...';

    // Filter functions
    const functions = abi.filter((item) => {
      if (item.type !== 'function') return false;
      if (!options.includeView && item.stateMutability === 'view') return false;
      if (!options.includePure && item.stateMutability === 'pure') return false;
      return true;
    });

    if (functions.length === 0) {
      spinner.warn('No functions found to scaffold');
      return;
    }

    // Generate handlers
    const handlers = functions.map((func) => generateHandler(contract, func));
    
    // Generate output
    const output = generateTargetFunctionsContract(contract, handlers);

    // Write output
    const outputPath = path.join(options.output || 'test/hunter', 'GeneratedHandlers.sol');
    await fs.ensureDir(path.dirname(outputPath));
    await fs.writeFile(outputPath, output);

    spinner.succeed(`Generated ${functions.length} handlers`);
    console.log(chalk.green(`\n📄 Output: ${outputPath}`));
    console.log(chalk.gray('\nGenerated handlers:'));
    functions.forEach((func) => {
      console.log(chalk.gray(`  - handler_${func.name}`));
    });

  } catch (error) {
    spinner.fail('Failed to scaffold handlers');
    console.error(chalk.red(error));
    process.exit(1);
  }
}

function generateHandler(contractName: string, func: ABIItem): string {
  const funcName = func.name!;
  const inputs = func.inputs || [];
  
  // Generate parameter list
  const params = inputs.map((input, i) => {
    const name = input.name || `arg${i}`;
    return `${solidityType(input.type)} ${name}`;
  }).join(', ');

  // Generate argument list for call
  const args = inputs.map((input, i) => input.name || `arg${i}`).join(', ');

  // Generate clamping for numeric types
  const clamping = inputs
    .filter((input) => isNumericType(input.type))
    .map((input, i) => {
      const name = input.name || `arg${i}`;
      if (input.type.startsWith('uint')) {
        return `        ${name} = between(${name}, 0, type(${input.type}).max);`;
      }
      return '';
    })
    .filter(Boolean)
    .join('\n');

  // Determine if we should use try/catch
  const useTryCatch = func.stateMutability !== 'view' && func.stateMutability !== 'pure';

  let body: string;
  if (useTryCatch) {
    body = `        __before();
        
        try ${contractName.toLowerCase()}.${funcName}(${args}) {
            __after();
            // Add post-condition assertions here
        } catch {
            // Handle expected reverts or mark as failure
            // t(false, "${funcName} reverted unexpectedly");
        }`;
  } else {
    body = `        __before();
        ${contractName.toLowerCase()}.${funcName}(${args});
        __after();`;
  }

  return `
    /// @notice Handler for ${contractName}.${funcName}
    function handler_${funcName}(${params}) public {
${clamping ? clamping + '\n' : ''}${body}
    }`;
}

function generateTargetFunctionsContract(
  contractName: string,
  handlers: string[]
): string {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// Generated by Invariant Hunter
// Contract: ${contractName}
// Generated at: ${new Date().toISOString()}

import {BaseTargetFunctions} from "invariant-hunter/BaseSetup.sol";
import {Properties} from "./Properties.sol";
// import {${contractName}} from "src/${contractName}.sol";

/// @title GeneratedHandlers - Auto-generated handlers for ${contractName}
/// @notice Copy these handlers to your TargetFunctions.sol and customize
abstract contract GeneratedHandlers is BaseTargetFunctions, Properties {
    // Uncomment and set the contract reference
    // ${contractName} public ${contractName.toLowerCase()};
${handlers.join('\n')}
}
`;
}

function solidityType(abiType: string): string {
  // Handle arrays
  if (abiType.endsWith('[]')) {
    return abiType.replace('[]', '[] memory');
  }
  // Handle bytes and string
  if (abiType === 'bytes' || abiType === 'string') {
    return `${abiType} memory`;
  }
  return abiType;
}

function isNumericType(type: string): boolean {
  return type.startsWith('uint') || type.startsWith('int');
}
